enum SharedPreferencesKeys {
  SP_ACCESS_TOKEN_KEY,
  SP_ACCOUNT_TYPE_KEY,
  SP_ACCOUNT_USERID_KEY,
  SP_ACCOUNT_NAME_KEY,
  SP_ACCOUNT_PHONE_KEY,
  SP_ACCOUNT_BALANCE_KEY,
  SP_ACCOUNT_POINTS_KEY,
  SP_ACCOUNT_IMAGE_KEY,
  SP_ACCOUNT_TOTAL_ORDERS_KEY,
  SP_LOCATION_PICKED,
  SP_USER_LOCATION
}
